name: Generate HTML via AI Trackers and Deploy 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 every Sunday

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r trackers/requirements.txt

    - name: Generate Research HTML
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        FREEPLAY_KEY: ${{ secrets.FREEPLAY_KEY }}
        FREEPLAY_PROJECT_ID: ${{ secrets.FREEPLAY_PROJECT_ID }}
        FREEPLAY_SUB_DOMAIN: ${{ secrets.FREEPLAY_SUB_DOMAIN }}
      run: |
        python3 trackers/research/main.py
    
    #- name: Generate News and Blogs HTML
      #env:
        #OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        #FREEPLAY_KEY: ${{ secrets.FREEPLAY_KEY }}
        #FREEPLAY_PROJECT_ID: ${{ secrets.FREEPLAY_PROJECT_ID }}
        #FREEPLAY_SUB_DOMAIN: ${{ secrets.FREEPLAY_SUB_DOMAIN }}
        #NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      #run: |
        #python3 trackers/news-and-blogs/main.py

    - name: Commit and Push
      run: |
        git config --global user.name 'jeremysilva1098'
        git config --global user.email 'jsilva1098@gmail.com'
        git add .
        git commit -m 'Update HTML files'
        git push

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: main # or 'main' if you are using /docs folder
        folder: .        # The folder your HTML files are in
